name: CI/CD Pipeline

on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        description: 'Project name'
        required: true
        type: string
      BUSINESS_GROUP:
        description: 'Project business group'
        default: 'ugii-corp'
        required: true
        type: string

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run project
        run: python main.py --project_name ${{inputs.PROJECT_NAME}} --business_group ${{inputs.BUSINESS_GROUP}}
            